# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-06 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meme', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('brand', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('op', models.IntegerField()),
                ('np', models.IntegerField()),
                ('img', models.CharField(max_length=100)),
                ('infoimg', models.CharField(max_length=100)),
            ],
        ),
    ]
